# Generated by Django 5.2.4 on 2025-07-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
